import React from 'react'
export const metadata = {
  title: "Setting pages",
  description: "Generated by create next app",
};
const dashboardlayout = ({ children }) => {
  return (
    <div>
      <ul className='flex p-3 gap-5'>
        <li>Setting</li>
        <li>Action</li>
      </ul>
      {children}
    </div>
  )
}

export default dashboardlayout